seed: 0
device: cuda:0
n_thread: 1
n_sample: 4096 # replay buffer size
max_explore_step: 5e4
base_dir: ""
pretrain_path: ""
tag: ""

env_type: mujoco
dim_c: 4
n_traj: 1
supervision: 0.0

mini_batch_size: 256
gamma: 0.99

log_interval: 1000
eval_interval: 20000

defaults:
  - _self_
  - alg: iql
  - env: CleanupSingle-v0
  - optional base_setting: "" # just to save a special_setting name to enable OmegaConf interpolation
  - optional special_setting: ${alg}/${base_setting} # actual yaml path for a special setting
